DocHub.Ui/Controllers/AppointmentsController.cs
using System.ComponentModel.DataAnnotations;
using System.Security.Claims;
using DocHub.Core.Domain.Entities.IdentityEntities;
using DocHub.Core.Domain.Models;
using DocHub.Core.Domain.RepositoryContracts;
using DocHub.Core.ServiceContracts;
using Microsoft.AspNetCore.Mvc;
using DocHub.Core.DTO;
using DocHub.Core.Enums.Appointments;
using DocHub.Ui.Session;
using Hangfire;
using Humanizer;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NuGet.Protocol;

namespace DocHub.Ui.Controllers;

[Route("[controller]/[action]")]
public class AppointmentsController : Controller
{
    private readonly IAppointmentsGetterService _appointmentsGetterService;
    private readonly IAppointmentsAdderService _appointmentsAdderService;
    private readonly IAppointmentsBookerService _appointmentsBookerService;
    private readonly IPatientsGetterService _patientsGetterService;
    private readonly UserManager<ApplicationUser> _userManager;
    private readonly IAppointmentsRepository _appointmentsRepository;
    private readonly IAppointmentsAddRangeService _appointmentsAddRangeService;
    private readonly IAppointmentUpdaterService _appointmentUpdaterService;
    private readonly IEmailSenderService _emailSender;
    private readonly IPrescriptionAdderService _prescriptionAdderService;
    private readonly IPrescriptionGetterService _prescriptionGetterService;
    private readonly IAppointmentsDeleterService _appointmentsDeleterService;
    private readonly IReferralsGetterService _referralsGetterService;
    private readonly IReferralsAdderService _referralsAdderService;

    public AppointmentsController(IAppointmentsGetterService appointmentsGetterService,
        IAppointmentsAdderService appointmentsAdderService, IAppointmentsBookerService appointmentsBookerService,
        IPatientsGetterService patientsGetterService, UserManager<ApplicationUser> userManager,
        IAppointmentsRepository appointmentsRepository, IAppointmentsAddRangeService appointmentsAddRangeService,
        IAppointmentUpdaterService appointmentUpdaterService, IEmailSenderService emailSender,
        IPrescriptionAdderService prescriptionAdderService, IPrescriptionGetterService prescriptionGetterService,
        IAppointmentsDeleterService appointmentsDeleterService,
        IReferralsGetterService referralsGetterService, IReferralsAdderService referralsAdderService)
    {
        _appointmentsGetterService = appointmentsGetterService;
        _appointmentsAdderService = appointmentsAdderService;
        _appointmentsBookerService = appointmentsBookerService;
        _patientsGetterService = patientsGetterService;
        _userManager = userManager;
        _appointmentsRepository = appointmentsRepository;
        _appointmentsAddRangeService = appointmentsAddRangeService;
        _appointmentUpdaterService = appointmentUpdaterService;
        _emailSender = emailSender;
        _prescriptionAdderService = prescriptionAdderService;
        _prescriptionGetterService = prescriptionGetterService;
        _appointmentsDeleterService = appointmentsDeleterService;
        _referralsGetterService = referralsGetterService;
        _referralsAdderService = referralsAdderService;
    }

    // GET
    [Authorize(Roles = "Admin, Patient")]
    public async Task<IActionResult> Index(int page = 1)
    {
        if (page < 1) page = 1;
        int pageSize = 5;

        var data = await _appointmentsGetterService.GetAll();
        var patients = await _patientsGetterService.GetAll();
        ViewBag.Patients = new SelectList(patients, "Id", "FullName");
        if (data != null)
        {
            var paginatedResult = PaginatedGroup<DateTime?, AppointmentResponse>.Create(
                data.Where(model => model.Start.Value.Date >= DateTime.Today),
                x => x.Start.Value.Date,
                page,
                pageSize
            );

            return View(paginatedResult);
        }

        return View();
    }

    [HttpGet]
    [Authorize(Roles = "Admin")]
    public IActionResult CreateAppointment()
    {
        return View();
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> CreateAppointment(AppointmentAddRequest request)
    {
        if (ModelState.IsValid)
        {
            var appointments = await _appointmentsRepository.GetAll();
            if (appointments != null)
            {
                var appointment = request.ToAppointment();
                var overlappingEntry = appointments
                    .Any(app =>
                        (appointment.Start >= app.Start && appointment.Start < app.End) ||
                        (appointment.End > app.Start && appointment.End <= app.End));
                if (overlappingEntry)
                {
                    ModelState.AddModelError("Start", "The appointment on the given date is already in the schedule");
                    return View(request);
                }
            }

            var createdAppointment = await _appointmentsAdderService.Add(request);
            TempData["SuccessMessage"] = "Appointment created.";
            return RedirectToAction(nameof(DashboardController.Index));
        }

        return View(request);
    }

    [Authorize(Roles = "Admin")]
    [HttpGet]
    [Route($"{{{nameof(appointmentId)}}}")]
    public async Task<IActionResult> Show(Guid appointmentId)
    {
        var response = await _appointmentsGetterService.Get(appointmentId);
        if (response is null) return RedirectToAction("Index");
        var patient = await _patientsGetterService.Get(response.PatientId);
        if (patient is null) return RedirectToAction("Index");

        return View(model: new AppointmentDetails() { AppointmentResponse = response, PatientResponse = patient });
    }

    [Authorize(Roles = "Patient")]
    [HttpPost]
    public async Task<IActionResult> ReserveAppointment(Guid appointmentId)
    {
        AppointmentResponse? response = await _appointmentsGetterService.Get(appointmentId);
        if (response is null)
        {
            return RedirectToAction("Index");
        }

        var user = await _userManager.GetUserAsync(User);
        if (user is null)
        {
            return RedirectToAction("Index");
        }

        var patient = await _patientsGetterService.GetByUserId(user.Id);
        if (patient is null)
        {
            return RedirectToAction("Index");
        }

        var request = new AppointmentReserveRequest() { PatientId = patient.Id, Id = appointmentId };
        var reserve = await _appointmentsBookerService.Reserve(request);
        if (reserve.PatientId is not null)
        {
            TimeSpan? diff = reserve.Start - DateTime.Now;
            if (diff.Value.TotalHours > 24)
            {
                DateTime reminderTime = reserve.Start.Value.AddHours(-24);      
                //DateTime reminderTime = DateTime.Now.AddSeconds(10);
                string message = $"Your visit will take place in: {reserve.Start.Value.Humanize()} \n Date of the visit: {reserve.Start.Value}";
                BackgroundJob.Schedule(
                    () => _emailSender.SendEmailAsync(patient.Email, "Appointment reminder",
                        message),
                    reminderTime);
            }
        }

        if (response.Start != null) TempData["SuccessMessage"] = "Appointment booked - " + response.Start.Value.Date;
        return RedirectToAction("Index");
    }

    [Authorize(Roles = "Admin")]
    [HttpGet]
    public IActionResult AddRange()
    {
        return View();
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]
    public async Task<IActionResult> AddRange(AppointmentAddRangeRequest request)
    {
        if (ModelState.IsValid)
        {
            var addRange = await _appointmentsAddRangeService.AddRange(request);
            TempData["test"] = addRange.Count;
            return RedirectToAction("Index");
        }

        return View(request);
    }

    [Authorize(Roles = "Admin")]
    [HttpGet]
    public async Task<IActionResult> StepOne(Guid appointmentId)
    {
        AppointmentResponse? response = await _appointmentsGetterService.Get(appointmentId);
        if (response is null) return RedirectToAction("Index", "Today");
        var patient = await _patientsGetterService.Get(response.PatientId);
        if (response.PatientId != null)
        {
            var finishedAppointments =
                await _appointmentsGetterService.GetAllFinishedPatientsAppointments(response.PatientId.Value);
            foreach (var item in finishedAppointments)
            {
                item.SetPrescriptions(_prescriptionGetterService.GetAllByAppointmentId(item.Id));
                item.SetReferrals(_referralsGetterService.GetAllByAppointmentId(item.Id));
            }

            ViewBag.AllAppointments = finishedAppointments.OrderByDescending(app => app.Start).ToList();
        }

        ViewData["Patient"] = patient;
        ViewData["Appointment"] = response;
        HttpContext.Session.SetObject<PatientResponse>("Patient", patient);
        HttpContext.Session.SetObject<AppointmentResponse>("Appointment", response);
        var updateRequestFromSession = HttpContext.Session.GetObject<AppointmentUpdateRequest>("StepOne");
        if (updateRequestFromSession == null)
        {
            AppointmentUpdateRequest updateRequest = response.ToAppointmentUpdateRequest();
            updateRequest.Prescriptions = new List<PrescriptionAddRequest>();
            updateRequest.Referrals = new List<ReferralAddRequest>();
            HttpContext.Session.SetObject("StepOne", updateRequest);
            return View(updateRequest);
        }

        return View(updateRequestFromSession);
    }

    [Authorize(Roles = "Admin")]
    [HttpPost]

DocHub.Ui/Controllers/DashboardController.cs
using DocHub.Core.DTO;
using DocHub.Core.ServiceContracts;
using DocHub.Ui.Session;
using Hangfire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DocHub.Ui.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

DocHub.Ui/Views/Appointments/CreateAppointment.cshtml
@model AppointmentAddRequest
@{
    Layout = "_DashboardLayout";
    ViewBag.CurrentUrl = "addapoitment";
}
<div class="max-w-md my-auto mx-auto bg-white p-8 rounded-lg shadow-md">
    <ul class="flex mb-4">
        <li class="mr-6">
            <a href="#" class="text-blue-500 hover:text-blue-700 border-b-2 border-blue-500 pb-2">One visit</a>
        </li>
        <li>
            <a asp-controller="Appointments" asp-action="AddRange" class="text-gray-500 hover:text-gray-700 border-b-2 border-transparent pb-2">Range</a>
        </li>
    </ul>
    <h1 class="text-2xl font-semibold mb-4 text-blue-500">Create appointment</h1>
    <nav class="flex" aria-label="Breadcrumb">
        <ol class="inline-flex items-center space-x-1 md:space-x-3">
            <li class="inline-flex items-center">
                <a asp-controller="Dashboard" asp-action="Index" class="inline-flex items-center text-sm font-medium text-gray-600 hover:text-blue-600 dark:text-gray-400">
                    <svg class="w-[12px] h-[12px] text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                        <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"/>
                    </svg>
                    &nbsp; Dashbaord
                </a>
            </li>
            <li>
                <div class="flex items-center">
                    <svg class="w-3 h-3 text-gray-600 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <p class="ml-1 text-sm font-medium hover:text-blue-700 md:ml-2 text-blue-600">Add appointment</p>
                </div>
            </li>
        </ol>
    </nav>
    <div class="border-b border-gray-200 my-4"></div>
    <form asp-action="CreateAppointment" asp-controller="Appointments" method="post">
        <div class="mb-4">
            <label asp-for="Start" class="block text-sm font-medium text-gray-600">Date of appointment</label>
            <div class="flex">
                <span class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border rounded-e-0 border-gray-300 rounded-s-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
                    <svg class="w-4 h-4 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path fill="currentColor" d="M6 1a1 1 0 0 0-2 0h2ZM4 4a1 1 0 0 0 2 0H4Zm7-3a1 1 0 1 0-2 0h2ZM9 4a1 1 0 1 0 2 0H9Zm7-3a1 1 0 1 0-2 0h2Zm-2 3a1 1 0 1 0 2 0h-2ZM1 6a1 1 0 0 0 0 2V6Zm18 2a1 1 0 1 0 0-2v2ZM5 11v-1H4v1h1Zm0 .01H4v1h1v-1Zm.01 0v1h1v-1h-1Zm0-.01h1v-1h-1v1ZM10 11v-1H9v1h1Zm0 .01H9v1h1v-1Zm.01 0v1h1v-1h-1Zm0-.01h1v-1h-1v1ZM10 15v-1H9v1h1Zm0 .01H9v1h1v-1Zm.01 0v1h1v-1h-1Zm0-.01h1v-1h-1v1ZM15 15v-1h-1v1h1Zm0 .01h-1v1h1v-1Zm.01 0v1h1v-1h-1Zm0-.01h1v-1h-1v1ZM15 11v-1h-1v1h1Zm0 .01h-1v1h1v-1Zm.01 0v1h1v-1h-1Zm0-.01h1v-1h-1v1ZM5 15v-1H4v1h1Zm0 .01H4v1h1v-1Zm.01 0v1h1v-1h-1Zm0-.01h1v-1h-1v1ZM2 4h16V2H2v2Zm16 0h2a2 2 0 0 0-2-2v2Zm0 0v14h2V4h-2Zm0 14v2a2 2 0 0 0 2-2h-2Zm0 0H2v2h16v-2ZM2 18H0a2 2 0 0 0 2 2v-2Zm0 0V4H0v14h2ZM2 4V2a2 2 0 0 0-2 2h2Zm2-3v3h2V1H4Zm5 0v3h2V1H9Zm5 0v3h2V1h-2ZM1 8h18V6H1v2Zm3 3v.01h2V11H4Zm1 1.01h.01v-2H5v2Zm1.01-1V11h-2v.01h2Zm-1-1.01H5v2h.01v-2ZM9 11v.01h2V11H9Zm1 1.01h.01v-2H10v2Zm1.01-1V11h-2v.01h2Zm-1-1.01H10v2h.01v-2ZM9 15v.01h2V15H9Zm1 1.01h.01v-2H10v2Zm1.01-1V15h-2v.01h2Zm-1-1.01H10v2h.01v-2ZM14 15v.01h2V15h-2Zm1 1.01h.01v-2H15v2Zm1.01-1V15h-2v.01h2Zm-1-1.01H15v2h.01v-2ZM14 11v.01h2V11h-2Zm1 1.01h.01v-2H15v2Zm1.01-1V11h-2v.01h2Zm-1-1.01H15v2h.01v-2ZM4 15v.01h2V15H4Zm1 1.01h.01v-2H5v2Zm1.01-1V15h-2v.01h2Zm-1-1.01H5v2h.01v-2Z"/>
                    </svg>
                </span>
                <input type="text" name="Start" datepicker datepicker-format="dd.mm.yyyy" value="@DateTime.Today.Date.ToString("dd.MM.yyyy")" class="rounded-none rounded-e-lg bg-white border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="@DateTime.Today.Date.ToString("dd.MM.yyyy")">
            </div>
            <span asp-validation-for="Start" class="text-red-500 text-sm"></span>
        </div>
        <div class="mb-4">
            <label asp-for="Hour" class="block text-sm font-medium text-gray-600">Time of appointment</label>
            <div class="flex">
                <span class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border rounded-e-0 border-gray-300 rounded-s-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
                    <svg class="w-4 h-4 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                        <path stroke="currentColor" stroke-linejoin="round" stroke-width="2" d="M10 6v4l3.276 3.276M19 10a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                    </svg>
                </span>
                <input asp-for="Hour" id="timeInput" class="rounded-none rounded-e-lg bg-white border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="08:00">
            </div>
        </div>
        <div class="mb-4">
            <label asp-for="Duration" class="block text-sm font-medium text-gray-600">Duration in minutes</label>
            <div class="flex">
                <span class="inline-flex items-center px-3 text-sm text-gray-900 bg-gray-200 border rounded-e-0 border-gray-300 rounded-s-md dark:bg-gray-600 dark:text-gray-400 dark:border-gray-600">
                    <svg class="w-4 h-4 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 16 20">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 1H1m14 18H1m2 0v-4.333a2 2 0 0 1 .4-1.2L5.55 10.6a1 1 0 0 0 0-1.2L3.4 6.533a2 2 0 0 1-.4-1.2V1h10v4.333a2 2 0 0 1-.4 1.2L10.45 9.4a1 1 0 0 0 0 1.2l2.15 2.867a2 2 0 0 1 .4 1.2V19H3Z"/>
                      </svg>
                </span>
                <input asp-for="Duration" max="1400" min="1" class="rounded-none rounded-e-lg bg-white border text-gray-900 focus:ring-blue-500 focus:border-blue-500 block flex-1 min-w-0 w-full text-sm border-gray-300 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="45 minutes">
            </div>
        </div>

        <div class="text-center flex mx-auto justify-between space-x-2">
            <div>
                <button type="submit" class="text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-blue-300 dark:focus:ring-blue-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Add</button>
            </div>
            <div class="flex">
                <button type="reset" class="py-2.5 px-5 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">Clear</button>
                <a asp-action="Index" asp-controller="Dashboard">
                    <div class="py-3.5 px-6 me-2 mb-2 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700">
                        <svg class="w-3 h-3 text-gray-800 " aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 14">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 6 6m0 0 6 6M7 7l6-6M7 7l-6 6"/>
                        </svg>
                    </div>
                </a>
            </div>
        </div>

    </form>

</div>

<script src="~/js/hourInput.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/datepicker.min.js"></script>

DocHub.Ui/Views/Appointments/DeleteAppointments.cshtml
@model List<AppointmentResponse>
@{
    Layout = "_DashboardLayout";
}
<div class="max-w-lg mx-auto bg-white rounded-md overflow-hidden shadow-md">
    <div class="p-4">
        <h1 class="text-2xl font-semibold mb-4 text-blue-500">Delete appointments</h1>
        <nav class="flex" aria-label="Breadcrumb">
            <ol class="inline-flex items-center space-x-1 md:space-x-3">
                <li class="inline-flex items-center">
                    <a asp-controller="Appointments" asp-action="Index" class="inline-flex items-center text-sm font-medium text-gray-600 hover:text-blue-600 dark:text-gray-400">
                        <svg class="w-[12px] h-[12px] text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                            <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"/>
                        </svg>
                        &nbsp; Schedule
                    </a>
                </li>
                <li>
                    <div class="flex items-center">
                        <svg class="w-3 h-3 text-gray-600 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                        </svg>
                        <p class="ml-1 text-sm font-medium hover:text-blue-700 md:ml-2 text-blue-600">Day: @Model[0].Start.Value.Date.ToString("dd.MM.yyyy")</p>
                    </div>
                </li>
            </ol>
        </nav>
        <hr class="mt-1 mb-1"/>
        <h3 class="font-semibold text-gray-700 text-sm">Choose appointments to delete</h3>
        <form asp-action="DeleteAppointmentsRange" method="post">
            <div class="flex flex-wrap">
                @for (int i = 0; i < Model.Count; i++)
                {
                    <div class="mb-1 me-1">
                        <input type="checkbox" name="ids" id="@Model[i].Id" value="@Model[i].Id" class="hidden peer">
                        <label for="@Model[i].Id" class="inline-flex items-center px-5 py-2.5 text-gray-500 bg-white border-2 border-gray-200 rounded-md cursor-pointer peer-checked:border-red-600 hover:text-gray-600 peer-checked:line-through peer-checked:text-red-600 hover:bg-gray-50 dark:text-gray-400">
                            <div>
                                <div class="text-xs font-semibold font-mono">@Model[i].Start.Value.ToString("HH:mm")</div>
                            </div>
                        </label>
                    </div>
                }
            </div>
            <div class="flex justify-between">
                <div class="my-auto">
                    <a asp-action="Index" asp-controller="Appointments" class="inline-flex text-xs text-gray-500 font-semibold hover:underline">
                        <svg class="w-6 h-6 text-gray-500 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m17 16-4-4 4-4m-6 8-4-4 4-4"/>
                        </svg>
                        <p class="my-auto">
                        back to schedule
                        </p>
                    </a>
                </div>

                <div>
                    <button type="submit" class="text-white bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 mb-2">Delete</button>
                </div>
            </div>
        </form>
    </div>
</div>