DocHub.Ui/Controllers/DashboardController.cs
using DocHub.Core.DTO;
using DocHub.Core.ServiceContracts;
using DocHub.Ui.Session;
using Hangfire;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace DocHub.Ui.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

DocHub.Ui/Controllers/MyPatientsController.cs
using DocHub.Core.Domain.Models;
using DocHub.Core.DTO;
using DocHub.Core.Enums.Appointments;
using DocHub.Core.Enums.Views;
using DocHub.Core.ServiceContracts;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;


namespace DocHub.Ui.Controllers
{
    [Authorize(Roles = "Doctor, Admin")]
    [Route("[controller]/[action]")]
    public class MyPatientsController : Controller
    {
        private readonly IPatientsGetterService _patientsGetterService;
        private readonly IPatientsAdderService _patientsAdderService;
        private readonly IPatientsSorterService _patientsSorterService;
        private readonly IPatientsSearcherService _patientsSearcherService;
        private readonly IAppointmentsGetterService _appointmentsGetterService;
        private readonly IPrescriptionGetterService _prescriptionGetterService;
        private readonly IReferralsGetterService _referralsGetterService;
        private readonly IPatientsUpdaterService _patientsUpdater;
        public MyPatientsController(IPatientsGetterService patientsGetterService,
            IPatientsAdderService patientsAdderService,
            IPatientsSorterService patientsSorterService,
            IPatientsSearcherService patientsSearcherService, IAppointmentsGetterService appointmentsGetterService,
            IPrescriptionGetterService prescriptionGetterService, IReferralsGetterService referralsGetterService, IPatientsUpdaterService patientsUpdater)
        {
            _patientsGetterService = patientsGetterService;
            _patientsAdderService = patientsAdderService;
            _patientsSorterService = patientsSorterService;
            _patientsSearcherService = patientsSearcherService;
            _appointmentsGetterService = appointmentsGetterService;
            _prescriptionGetterService = prescriptionGetterService;
            _referralsGetterService = referralsGetterService;
            _patientsUpdater = patientsUpdater;
        }

        public async Task<IActionResult> Index(string? query,
            string sortBy = nameof(PatientResponse.FullName),
            SortOrderOptions sortOrder = SortOrderOptions.Asc)
        {
            var filteredPatients =
                await _patientsSearcherService.Search(query);
            var sortedPatients =
                await _patientsSorterService.GetSortedPatients(filteredPatients, sortBy, sortOrder);
            ViewBag.CurrentSortBy = sortBy;
            ViewBag.CurrentSortOrder = sortOrder.ToString();
            ViewBag.CurrentQuery = query;
            ;
            return View(sortedPatients);
        }

        [HttpGet]
        public IActionResult CreatePatient()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreatePatient(PatientAddRequest request)
        {
            if (ModelState.IsValid)
            {
                var addedPatient = await _patientsAdderService.AddPatient(request);
                TempData["SuccessMessage"] = "Patient added.";
                return RedirectToAction(nameof(MyPatientsController.Index));
            }

            return View(request);
        }
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id is null) return RedirectToAction("Index");
            var patient = await _patientsGetterService.Get(id);
            if (patient is null) return RedirectToAction("Index");
            var model = new PatientUpdateRequest()
            {
                Id = patient.Id,
                FirstName = patient.FirstName,
                LastName = patient.LastName,
                Email = patient.Email,
                PeselNumber = patient.PeselNumber,
                PhoneNumber = patient.PhoneNumber,
                DateOfBirth = patient.DateOfBirth,
                City = patient.City,
                PostalCode = patient.PostalCode,
                Address = patient.Address,
                TakenMedications = patient.TakenMedications,
                Allergies = patient.Allergies,
                HistoryOfDiseases = patient.HistoryOfDseases,
            };
            return View(model);

        }

        public async Task<IActionResult> Edit(PatientUpdateRequest? request)
        {
            if (request is null) return RedirectToAction("Index");
            if (ModelState.IsValid)
            {
                var updatedPatient = await _patientsUpdater.UpdatePatient(request);
            }

            return View(request);
        }

        [Route($"{{id:guid}}")]
        [HttpGet]
        public async Task<IActionResult> ShowProfile(Guid? id)
        {
            if (id is null) return RedirectToAction("Index");
            var matchingPatient = await _patientsGetterService.Get(id);
            if (matchingPatient is null) return RedirectToAction("Index");
            var patient = await _patientsGetterService.Get(id);
            var appointments = await _appointmentsGetterService.GetAllPatientsAppointments(matchingPatient.Id);
            var sortedAppointments = appointments.OrderBy(model =>
                    model.State == State.Finished ? 0 : (model.State == State.Reserved ? 1 : 2))
                .ThenByDescending(
                    app =>
                    {
                        if (app.Start != null) return app.Start.Value;
                        throw new ArgumentException();
                    });
            foreach (var item in appointments)
            {
                var prescriptions = _prescriptionGetterService.GetAllByAppointmentId(item.Id);
                var referrals = _referralsGetterService.GetAllByAppointmentId(item.Id);
                item.SetPrescriptions(prescriptions);
                item.SetReferrals(referrals);
            }

            var model = new Profile()
            {
                Patient = patient,
                Appointments = sortedAppointments
            };
            return View(model);
        }
    }
}

DocHub.Ui/Views/MyPatients/Index.cshtml
@using DocHub.Core.Domain.Entities
@model IEnumerable<PatientResponse>
@{
    Layout = "_DashboardLayout";
    ViewBag.Title = "My patients";
    ViewBag.CurrentUrl = "mypatients/index";

}
<form asp-controller="MyPatients" asp-action="Index" method="get">
    <section class="bg-gray-50 p-3 sm:p-5">
        <div class="mx-auto max-w-screen-xl px-4 lg:px-12">
            <div class="bg-white relative shadow-md rounded-lg overflow-hidden">
                <h1 class="text-2xl font-semibold mb-4 text-blue-500 pl-3 pt-3">Patients</h1>
                <nav class="flex pl-3" aria-label="Breadcrumb">
                    <ol class="inline-flex items-center space-x-1 md:space-x-3">
                        <li class="inline-flex items-center">
                            <a asp-controller="Dashboard" asp-action="Index" class="inline-flex items-center text-sm font-medium text-gray-700 hover:text-blue-600 dark:text-gray-400">
                                <svg class="w-[12px] h-[12px] text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 18 18">
                                    <path d="M6.143 0H1.857A1.857 1.857 0 0 0 0 1.857v4.286C0 7.169.831 8 1.857 8h4.286A1.857 1.857 0 0 0 8 6.143V1.857A1.857 1.857 0 0 0 6.143 0Zm10 0h-4.286A1.857 1.857 0 0 0 10 1.857v4.286C10 7.169 10.831 8 11.857 8h4.286A1.857 1.857 0 0 0 18 6.143V1.857A1.857 1.857 0 0 0 16.143 0Zm-10 10H1.857A1.857 1.857 0 0 0 0 11.857v4.286C0 17.169.831 18 1.857 18h4.286A1.857 1.857 0 0 0 8 16.143v-4.286A1.857 1.857 0 0 0 6.143 10Zm10 0h-4.286A1.857 1.857 0 0 0 10 11.857v4.286c0 1.026.831 1.857 1.857 1.857h4.286A1.857 1.857 0 0 0 18 16.143v-4.286A1.857 1.857 0 0 0 16.143 10Z"/>
                                </svg>
                                &nbsp; Dashbaord
                            </a>
                        </li>
                        <li>
                            <div class="flex items-center">
                                <svg class="w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                                </svg>
                                <p class="ml-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ml-2">Profil</p>
                            </div>
                        </li>
                    </ol>
                </nav>
                <div class="flex flex-col md:flex-row items-center justify-between space-y-3 md:space-y-0 md:space-x-4 p-4">
                    <div class="w-full md:w-1/2">
                        <div class="flex items-center">
                            <label class="sr-only">Search</label>
                            <div class="relative w-full">
                                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                                    <svg aria-hidden="true" class="w-5 h-5 text-gray-500" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                        <path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"/>
                                    </svg>
                                </div>

                                <input type="search" name="query" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full pl-10 p-2" placeholder="Search" required="" value="@ViewBag.CurrentQuery">
                            </div>
                        </div>
                    </div>
                    <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
                        <button type="submit" class="flex items-center justify-center text-gray-900 bg-gray-50 border hover:bg-gray-100 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 focus:outline-none">
                            <svg class="h-3.5 w-3.5 mr-2  text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
                            </svg>
                            Search
                        </button>
                    </div>
                    <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
                        <a asp-action="Index" class="flex items-center justify-center text-gray-900 bg-gray-50 border hover:bg-gray-100 focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 focus:outline-none">
                            <svg class="h-3.5 w-3.5 mr-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m13 7-6 6m0-6 6 6m6-3a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/>
                            </svg>
                            Clear
                        </a>
                    </div>
                    <div class="w-full md:w-auto flex flex-col md:flex-row space-y-2 md:space-y-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0">
                        <a asp-action="CreatePatient" class="flex items-center justify-center text-white bg-gradient-to-r from-blue-500 via-blue-600 to-blue-700 hover:bg-gradient-to-br  focus:ring-4 focus:ring-primary-300 font-medium rounded-lg text-sm px-4 py-2 focus:outline-none">
                            <svg class="h-3.5 w-3.5 mr-2" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
                                <path clip-rule="evenodd" fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z"/>
                            </svg>
                            Add patient
                        </a>
                    </div>
                </div>
                <div class="overflow-x-auto">
                    <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
                        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                        <tr>
                            @await Html.PartialAsync("_GridColumnHeader", new ViewDataDictionary(ViewData)
                                   {
                                       { "ColumnName", nameof(PatientResponse.FullName) },
                                       { "DisplayName", "Full name" }
                                   })
                            <th scope="col" class="px-4 py-3">PESEL</th>
                            <th scope="col" class="px-4 py-3">Email address</th>
                            <th scope="col" class="px-4 py-3">
                                <span class="sr-only">Actions</span>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach (var patient in Model)
                        {
                            var dropdown = String.Concat(patient.Id, "dropdown");
                            var dropdownButton = String.Concat(patient.Id, "dropdown", "button");
                            <tr class="border-b dark:border-gray-700">
                                <th scope="row" class="px-4 py-3 font-medium text-gray-900 whitespace-nowrap dark:text-white">@patient.FullName</th>
                                @if (string.IsNullOrEmpty(patient.PeselNumber))
                                {
                                    <td class="px-4 py-3 italic">Empty</td>
                                }
                                else
                                {
                                    <td class="px-4 py-3">@patient.PeselNumber</td>
                                }
                                <td class="px-4 py-3">@patient.Email</td>
                                <td class="px-4 py-3 flex items-center justify-end">
                                    <button id="@dropdownButton" data-dropdown-toggle="@dropdown" class="inline-flex items-center p-0.5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100" type="button">
                                        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z"/>
                                        </svg>
                                    </button>
                                    <div id="@dropdown" class="hidden z-10 w-44 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                                        <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="@dropdownButton">
                                            <li>
                                                <a asp-action="ShowProfile" asp-route-id="@patient.Id" class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Show</a>
                                            </li>
                                            <li>
                                                <a asp-action="Edit" asp-route-id="@patient.Id" class="block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Edit</a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
</form>